### ISSUE TITLE
Start vue.js app to provide visualisation

### ISSUE THREAD

**Issue by willnotwish** [willnotwish/at-the-races#20]
I have an event source and some very basic vanilla js logging functionality.

First task is to add a very simple vue.js app to replace this.

It needs to filter those incoming events which do not relate to the race being monitored.

**Comment by willnotwish** [comment]
As usual I am confused by all the javascript build systems. Although I would prefer not to use webpacker, I found this article

https://medium.com/prolific-programmer/rails-4-2-webpacker-vue-and-jest-23e1d00c5825

**Comment by willnotwish** [comment]
I am going on a (short, hopefully) detour with [vite](https://vite.dev/)

**Comment by willnotwish** [comment]
For a start I need a node.js container...

**Comment by willnotwish** [comment]
After some tedious setup, I got this to work

```
  atr-viz:
    image: node:20
    secrets:
      - pubnub
    volumes:
      - ./apps/atr-viz:/app
    stdin_open: true
    tty: true
    user: node
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    ports:
      - 5173:5173
```
Note the -- after `npm run dev`.

Now I see
![image](https://github.com/user-attachments/assets/e195dc52-596a-485b-9ce1-a7243d42998b)

I'm not sure I could do that again in a hurry but it's working for now at least.
